### PR TITLE
Fixed bitwise handling of angle range

### PR DESCRIPTION
**Pull request by dogramacigokhan**

### CODE REVIEW

**Comment by Aravind-Suresh** [comment]
@dogramacigokhan This seems fine. It adds portability to combination of angle ranges. Cool :). Just squash the 2 commits and push. So that I can merge.

**Comment by dogramacigokhan** [comment]
Done! Thanks :)

**Comment by Aravind-Suresh** [comment]
Okay. But I am not sure about how to go about. I will merge this pull request. But then I have to squash this commit along with mine for OpenCV. Then it will be commited under my name only. Is there any other way so as to give credits/recognition for your work?

**Comment by dogramacigokhan** [comment]
I think this would be an exception for squashing the commits. But if you have to, it's okay; no need to give credits :)

**Comment by Aravind-Suresh** [comment]
Ohh is it? Sorry, I haven't tried merging pull requests on forks. But I will try my best to give you credits. And thanks for the fix :+1:

**Comment by Aravind-Suresh** [comment]
I merged, squashed and pushed. Hence, closing the pull request. Thanks :)

**Comment by dogramacigokhan** [comment]
@Aravind-Suresh 

Is it okay to add me this project as collaborator? So I can push my changes directly to your pull request. I will do some bug-fixes and add custom angle range support, custom angle step defining instead of 1 etc.

**Pull request closed without merging**
